services:
  backend:
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: REDACTED
      MYSQL_PORT: 3306
      MYSQL_USER: examitsu
      MYSQL_PASSWORD: REDACTED
      MYSQL_DATABASE: examitsu
      REDIS_HOST: REDACTED
      REDIS_PORT: 6379
      GORM_LOG_LEVEL: 4
      JWT_SIGNATURE_KEY: REDACTED
      SYSTEM_PASSWORD: REDACTED
      PROCTOR_PASSWORD: REDACTED
      STORAGE_SERVICE_ACCOUNT_KEY_PATH: /etc/secret/gcs-service-account.json
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "3"
    volumes:
      - /REDACTED/secret:/etc/secret

  backend-worker:
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - backend-mysql
      - backend-redis
    environment:
      ROLE: worker
      MYSQL_HOST: backend-mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: examitsu
      REDIS_HOST: backend-redis
      REDIS_PORT: 6379
      GORM_LOG_LEVEL: 4
    networks:
      - private
    ports:
      - 3306:3306
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "3"

  backend-redis:
    restart: always
    image: redis:7.0
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    networks:
      - private
    ports:
      - 6379:6379
    volumes:
      - backend_redis_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "3"

  backend-mysql:
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_USER: examitsu
      MYSQL_PASSWORD: REDACTED
      MYSQL_DATABASE: examitsu
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - backend_mysql_data:/var/lib/mysql
    networks:
      - private
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "3"

  frontend:
    restart: always
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: https://examitsu.net
        REACT_APP_HOST_BASE_URL: https://examitsu.net
    ports:
      - "3000:3000"

volumes:
  backend_redis_data:
  backend_mysql_data:

networks:
  private: