CREATE TABLE exams(
    id BIGINT NOT NULL AUTO_INCREMENT,
    
    serial VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_open TINYINT(1) NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    not_archived BOOLEAN GENERATED ALWAYS AS (IF(deleted_at IS NULL, 1, NULL)) VIRTUAL,

    CONSTRAINT PK_id PRIMARY KEY (id),
	CONSTRAINT UC_serial UNIQUE (serial, not_archived)
);

CREATE TABLE questions(
    id BIGINT NOT NULL AUTO_INCREMENT,
    
    exam_id BIGINT NOT NULL,
    order_number BIGINT NOT NULL DEFAULT 0,
    data LONGTEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,

    CONSTRAINT PK_id PRIMARY KEY (id),
    CONSTRAINT FOREIGN KEY (exam_id) REFERENCES exams(id)
);

CREATE TABLE mcq_options(
    id BIGINT NOT NULL AUTO_INCREMENT,

    question_id BIGINT NOT NULL,
    description TEXT,
    point INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,

    CONSTRAINT PK_id PRIMARY KEY (id),
    CONSTRAINT FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE TABLE participants(
    id BIGINT NOT NULL AUTO_INCREMENT,

    exam_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    started_at TIMESTAMP,
    ended_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    not_archived BOOLEAN GENERATED ALWAYS AS (IF(deleted_at IS NULL, 1, NULL)) VIRTUAL,

    CONSTRAINT PK_id PRIMARY KEY (id),
    CONSTRAINT FOREIGN KEY (exam_id) REFERENCES exams(id),
    CONSTRAINT UNIQUE (exam_id, name, not_archived)
);

CREATE TABLE submissions(
    id BIGINT NOT NULL AUTO_INCREMENT,

    participant_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    mcq_option_id BIGINT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    not_archived BOOLEAN GENERATED ALWAYS AS (IF(deleted_at IS NULL, 1, NULL)) VIRTUAL,

    CONSTRAINT PRIMARY KEY (id),
    CONSTRAINT FOREIGN KEY (participant_id) REFERENCES participants(id),
    CONSTRAINT FOREIGN KEY (question_id) REFERENCES questions(id),
    CONSTRAINT FOREIGN KEY (mcq_option_id) REFERENCES mcq_options(id),
    CONSTRAINT UNIQUE (participant_id, question_id, not_archived)
);