CREATE TABLE exams(
    id BIGINT NOT NULL AUTO_INCREMENT,
    
    serial VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_open TINYINT(1) NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,

    CONSTRAINT PK_id PRIMARY KEY (id),
	CONSTRAINT UC_serial UNIQUE (serial)
);

CREATE TABLE questions(
    id BIGINT NOT NULL AUTO_INCREMENT,
    
    exam_id BIGINT NOT NULL,
    order_number BIGINT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,

    CONSTRAINT PK_id PRIMARY KEY (id),
    CONSTRAINT FOREIGN KEY (exam_id) REFERENCES exams(id)
);

CREATE TABLE question_images(
    id BIGINT NOT NULL AUTO_INCREMENT,

    question_id BIGINT NOT NULL,
    image_url TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,

    CONSTRAINT PK_id PRIMARY KEY (id),
    CONSTRAINT FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE TABLE mcq_options(
    id BIGINT NOT NULL AUTO_INCREMENT,

    question_id BIGINT NOT NULL,
    description TEXT,
    point INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,

    CONSTRAINT PK_id PRIMARY KEY (id),
    CONSTRAINT FOREIGN KEY (question_id) REFERENCES questions(id)
);